# Experiment 12
### Name- Shreya
### PRN- 25070123159
### Batch- A3
### Title- Data Wrangling

To perform preprocessing on a dataset and Dealing with Missing Values

In [1]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'C1':[11,21,np.nan],'C2':[12,13,np.nan],'C3':[10,20,30]})

     C1    C2  C3
0  11.0  12.0  10
1  21.0  13.0  20
2   NaN   NaN  30

In [3]:
df1

     C1    C2  C3
0  11.0  12.0  10
1  21.0  13.0  20
2   NaN   NaN  30

In [10]:
df1.isna() #Boolean Function

      C1     C2     C3
0  False  False  False
1  False  False  False
2   True   True  False

In [6]:
df1.notna()

      C1     C2    C3
0   True   True  True
1   True   True  True
2  False  False  True

In [8]:
df1.isna().sum()

C1    1
C2    1
C3    0
dtype: int64

In [9]:
df1.dropna() # NaN rows are dropped

     C1    C2  C3
0  11.0  12.0  10
1  21.0  13.0  20

In [11]:
df1.fillna(value='Default')

        C1       C2  C3
0     11.0     12.0  10
1     21.0     13.0  20
2  Default  Default  30

In [13]:
df1.fillna(df1.mean()) #Mean values of columns are calculated

     C1    C2  C3
0  11.0  12.0  10
1  21.0  13.0  20
2  16.0  12.5  30

In [27]:
# Preprocessing on Dataset1
import pandas as pd
data={
    "RollNo":[101,102,103,104,105],
    "Name":["A","B","C","D","E"],
    "Marks":[90,80,70,70,"."],
    "Age":[20,19,18,19,20],
    "Department":["Cse","Mech","Civil","Ece","Mech"],
    "Admission_Date":["01-06-2023","02-03-2023","03-08-2023",".","15-06-2023"]
}
df1=pd.DataFrame(data)

#Save as CSV
df1.to_csv("student_data.csv",index=False)

In [28]:
import pandas as pd
import numpy as np

#Step 1: Load the dataset
df=pd.read_csv("student_data.csv")
print("Original Data:")
df

Original Data:

   RollNo Name Marks  Age Department Admission_Date
0     101    A    90   20        Cse     01-06-2023
1     102    B    80   19       Mech     02-03-2023
2     103    C    70   18      Civil     03-08-2023
3     104    D    70   19        Ece              .
4     105    E     .   20       Mech     15-06-2023

In [29]:
# Step 2: Replace "." with NaN to mark missing values
df.replace(".",np.nan,inplace=True)
df

   RollNo Name Marks  Age Department Admission_Date
0     101    A    90   20        Cse     01-06-2023
1     102    B    80   19       Mech     02-03-2023
2     103    C    70   18      Civil     03-08-2023
3     104    D    70   19        Ece            NaN
4     105    E   NaN   20       Mech     15-06-2023

In [32]:
#Convert columns to numeric wherever needed
df["Age"]=pd.to_numeric(df["Age"],errors="coerce")
df["Marks"]=pd.to_numeric(df["Marks"],errors="coerce")
df

'''When converting data (like strings to datetime),
if some values are invalidor can not be converted,
instead of throwing an error,it will:
replace those invalid values with NaT(Not a Time)'''
df

   RollNo Name  Marks  Age Department Admission_Date
0     101    A   90.0   20        Cse     01-06-2023
1     102    B   80.0   19       Mech     02-03-2023
2     103    C   70.0   18      Civil     03-08-2023
3     104    D   70.0   19        Ece            NaN
4     105    E    NaN   20       Mech     15-06-2023

In [34]:
#Step 3: Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
RollNo            0
Name              0
Marks             1
Age               0
Department        0
Admission_Date    1
dtype: int64

In [36]:
# Step 4: Fill missing Age with mean
df["Age"].fillna(df["Age"].mean(),inplace=True)

/tmp/ipykernel_199/1207222351.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)

In [37]:
df

   RollNo Name  Marks  Age Department Admission_Date
0     101    A   90.0   20        Cse     01-06-2023
1     102    B   80.0   19       Mech     02-03-2023
2     103    C   70.0   18      Civil     03-08-2023
3     104    D   70.0   19        Ece            NaN
4     105    E    NaN   20       Mech     15-06-2023

In [43]:
#Step 5: Fix inconsistent text formatting
df["Department"]=df["Department"].str.upper()
df

   RollNo Name  Marks  Age Department Admission_Date
0     101    A   90.0   20        CSE     2023-01-06
1     102    B   80.0   19       MECH     2023-02-03
2     103    C   70.0   18      CIVIL     2023-03-08
3     104    D   70.0   19        ECE            NaT
4     105    E    NaN   20       MECH            NaT

In [38]:
print(df.isnull().sum())

RollNo            0
Name              0
Marks             1
Age               0
Department        0
Admission_Date    1
dtype: int64

In [42]:
#Step 6: Convert Admission Date to standard Datetime format
df["Admission_Date"]=pd.to_datetime(df["Admission_Date"],errors="coerce")
df

   RollNo Name  Marks  Age Department Admission_Date
0     101    A   90.0   20        Cse     2023-01-06
1     102    B   80.0   19       Mech     2023-02-03
2     103    C   70.0   18      Civil     2023-03-08
3     104    D   70.0   19        Ece            NaT
4     105    E    NaN   20       Mech            NaT

In [44]:
# Step 7: Show Cleaned Data
print("\nCleaned Data")
df

Cleaned Data

   RollNo Name  Marks  Age Department Admission_Date
0     101    A   90.0   20        CSE     2023-01-06
1     102    B   80.0   19       MECH     2023-02-03
2     103    C   70.0   18      CIVIL     2023-03-08
3     104    D   70.0   19        ECE            NaT
4     105    E    NaN   20       MECH            NaT

In [45]:
#Step 8: Save Cleaned Dataset
df.to_csv("Cleaned_Student_data.csv",index=False)
print("\nCleaned CSV file saved as cleaned_student_data.csv")

Cleaned CSV file saved as cleaned_student_data.csv

In [46]:
# Working with missing values on Dataset 2
df=pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [47]:
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [50]:
# Imputing the missing value
# 1. Lugguage rooom
df['Luggage.room'].fillna(df['Luggage.room'].mean(),inplace=True)
df

/tmp/ipykernel_199/556208229.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Luggage.room'].fillna(df['Luggage.room'].mean(),inplace=True)

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [52]:
# 2. Rear Seat Room
df["Rear.seat.room"]=df["Rear.seat.room"].fillna(value=df["Rear.seat.room"].mean())
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [56]:
# 3. Airbag
df["AirBags"]=df["AirBags"].fillna(value=df["AirBags"].mode().values[0])
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,Driver only,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,Driver only,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,Driver only,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [58]:
# Save Cleaned Dataset
df.to_csv("Cleaned_Cars93.csv",index=False)