# Experiment 11
### Name- Shreya
### PRN- 25070123159
### Batch- A3
### Title- Categorial Data Analysis Using Python

In [16]:
import pandas as pd
data={
'Order_ID':['01','02','03','04','05','06','07','08','09','010'],
       'Category':['Furniture','Office Supplies','Furniture','Technology','Technology','Furniture','Office Supplies','Furniture','Technology','Technology'],
       'Payment_Mode':['COD','COD','UPI','COD','UPI','COD','COD','UPI','COD','UPI'],
       'Delivery_Type':['Express','Standard','Express','Standard','Express','Standard','Express','Standard','Express','Standard'],
       'Customer_Type':['New','Returning','New','Returning','New','New','Returning','New','Returning','New']
}
df=pd.DataFrame(data)
df

  Order_ID         Category Payment_Mode Delivery_Type Customer_Type
0       01        Furniture          COD       Express           New
1       02  Office Supplies          COD      Standard     Returning
2       03        Furniture          UPI       Express           New
3       04       Technology          COD      Standard     Returning
4       05       Technology          UPI       Express           New
5       06        Furniture          COD      Standard           New
6       07  Office Supplies          COD       Express     Returning
7       08        Furniture          UPI      Standard           New
8       09       Technology          COD       Express     Returning
9      010       Technology          UPI      Standard           New

In [13]:
#Frequency Count
#Count how many orders in each category
print(df['Category'].value_counts())
print( df['Payment_Mode'].value_counts())
print(df['Delivery_Type'].value_counts())

Category
Furniture          4
Technology         4
Office Supplies    2
Name: count, dtype: int64
Payment_Mode
COD    6
UPI    4
Name: count, dtype: int64
Delivery_Type
Express     5
Standard    5
Name: count, dtype: int64

In [12]:
#Unique Values
#Display all unique categories
print(df['Category'].unique())
print(df['Payment_Mode'].unique())
print(df['Delivery_Type'].unique())
print(df['Customer_Type'].unique())

['Furniture' 'Office Supplies' 'Technology']
['COD' 'UPI']
['Express' 'Standard']
['New' 'Returning']

In [20]:
#Number of Unique Values
print(df['Category'].nunique())
print(df['Payment_Mode'].nunique())
print(df['Delivery_Type'].nunique())
print(df['Customer_Type'].nunique())

3
2
2
2

In [21]:
#Cross Tabulation
#Category vs Payment Method
print(pd.crosstab(df['Category'],df['Payment_Mode']))

Payment_Mode     COD  UPI
Category
Furniture          2    2
Office Supplies    2    0
Technology         2    2

In [23]:
#Cross Tabulation
#Delivery Type vs Customer Type
print(pd.crosstab(df['Delivery_Type'],df['Customer_Type']))

Customer_Type  New  Returning
Delivery_Type
Express          3          2
Standard         3          2

In [24]:
#Percentage Distribution
print(df['Category'].value_counts(normalize=True)*100)

Category
Furniture          40.0
Technology         40.0
Office Supplies    20.0
Name: proportion, dtype: float64

In [25]:
#Filtering Data
#Orders from Electronics Category
print(df[df['Category']=='Furniture'])

  Order_ID   Category Payment_Mode Delivery_Type Customer_Type
0       01  Furniture          COD       Express           New
2       03  Furniture          UPI       Express           New
5       06  Furniture          COD      Standard           New
7       08  Furniture          UPI      Standard           New

In [28]:
#Grouping
#Orders by Category and Payment Method
print(df.groupby('Category')['Payment_Mode'].value_counts())

Category         Payment_Mode
Furniture        COD             2
                 UPI             2
Office Supplies  COD             2
Technology       COD             2
                 UPI             2
Name: count, dtype: int64

In [29]:
#Sorting Data
sorted_df=df.sort_values(by='Category')
print(sorted_df)

  Order_ID         Category Payment_Mode Delivery_Type Customer_Type
0       01        Furniture          COD       Express           New
2       03        Furniture          UPI       Express           New
5       06        Furniture          COD      Standard           New
7       08        Furniture          UPI      Standard           New
1       02  Office Supplies          COD      Standard     Returning
6       07  Office Supplies          COD       Express     Returning
3       04       Technology          COD      Standard     Returning
4       05       Technology          UPI       Express           New
8       09       Technology          COD       Express     Returning
9      010       Technology          UPI      Standard           New

In [30]:
#Second Dataset
df=pd.read_csv('/content/Expt11.csv')
df

   Student  Gender  Department Grade
0       S1    Male         CSE     A
1       S2  Female          IT     B
2       S3  Female         CSE     A
3       S4    Male         ECE     C
4       S5    Male          IT     B
5       S6  Female         CSE     A
6       S7    Male  Mechanical     B
7       S8  Female          IT     A
8       S9    Male         CSE     C
9      S10  Female         ECE     B
10     S11    Male         CSE     A
11     S12  Female          IT     B
12     S13    Male  Mechanical     C
13     S14  Female         CSE     A
14     S15    Male          IT     B
15     S16  Female         ECE     A
16     S17    Male         CSE     B
17     S18  Female          IT     C
18     S19    Male  Mechanical     B
19     S20  Female         CSE     A
20     S21    Male         ECE     C
21     S22  Female          IT     B
22     S23    Male         CSE     A
23     S24  Female  Mechanical     B
24     S25    Male          IT     A
25     S26  Female         CSE     C
26     S27    Male         ECE     B
27     S28  Female          IT     A
28     S29    Male  Mechanical     C
29     S30  Female         CSE     B
30     S31    Male          IT     A
31     S32  Female         ECE     B
32     S33    Male         CSE     A
33     S34  Female  Mechanical     C
34     S35    Male          IT     B
35     S36  Female         CSE     A
36     S37    Male         ECE     B
37     S38  Female          IT     C
38     S39    Male  Mechanical     B
39     S40  Female         CSE     A
40     S41    Male          IT     B
41     S42  Female         ECE     A
42     S43    Male         CSE     C
43     S44  Female  Mechanical     B
44     S45    Male          IT     A
45     S46  Female         CSE     B
46     S47    Male         ECE     C
47     S48  Female          IT     A
48     S49    Male  Mechanical     B
49     S50  Female         CSE     A
50     S51    Male          IT     B
51     S52  Female         ECE     C
52     S53    Male         CSE     A
53     S54  Female  Mechanical     B
54     S55    Male          IT     C
55     S56  Female         CSE     A
56     S57    Male         ECE     B
57     S58  Female          IT     A
58     S59    Male  Mechanical     C
59     S60  Female         CSE     B

In [31]:
print(df.head())

  Student  Gender Department Grade
0      S1    Male        CSE     A
1      S2  Female         IT     B
2      S3  Female        CSE     A
3      S4    Male        ECE     C
4      S5    Male         IT     B

In [36]:
#Count Students in each grade
#Find how many students obtained each grade
print('Grade Frequeny')
print(df['Grade'].value_counts())

Grade Frequeny
Grade
B    24
A    22
C    14
Name: count, dtype: int64

In [39]:
#Percentage Distribution of Grade
print(df['Grade'].value_counts(normalize=True)*100)

Grade
B    40.000000
A    36.666667
C    23.333333
Name: proportion, dtype: float64

In [41]:
#Number of Students in each Deapartment
print(df['Department'].value_counts())

Department
CSE           20
IT            18
ECE           11
Mechanical    11
Name: count, dtype: int64

In [46]:
#Gender Distribution
print(pd.crosstab(df['Gender'],df['Department']))

Department  CSE  ECE  IT  Mechanical
Gender
Female       12    5   9           4
Male          8    6   9           7

In [47]:
#Gender vs Grade Analysis
print(pd.crosstab(df['Gender'],df['Grade']))

Grade    A   B  C
Gender
Female  14  11  5
Male     8  13  9

In [48]:
#Department vs Grade Percentage
print(pd.crosstab(df['Department'],df['Grade'],normalize=True)*100)

Grade               A          B         C
Department
CSE         21.666667   6.666667  5.000000
ECE          3.333333   8.333333  6.666667
IT          11.666667  13.333333  5.000000
Mechanical   0.000000  11.666667  6.666667

In [50]:
#Grouping Data (Departmentwise)
print(df.groupby('Department')['Grade'].value_counts())

Department  Grade
CSE         A        13
            B         4
            C         3
ECE         B         5
            C         4
            A         2
IT          B         8
            A         7
            C         3
Mechanical  B         7
            C         4
Name: count, dtype: int64