# Experiment 14
### Name- Shreya
### PRN- 25070123159
### Batch- A3
### Title- Data Normalization and Data Type Conversion

#**Part A: Data Normalization**

In [8]:
#Dataset
import pandas as pd
import numpy as np

data= {'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
       'Price':[55000,30000,67000,30000,55600,45000],
       'Units_sold':[25,45,67,89,65,34],
       'Discount':[10,20,15,25,10,5]}
df=pd.DataFrame(data)
print(df)

      Product  Price  Units_sold  Discount
0      Laptop  55000          25        10
1      Mobile  30000          45        20
2      Tablet  67000          67        15
3  Headphones  30000          89        25
4  Smartwatch  55600          65        10
5      Camera  45000          34         5

In [10]:
#1. Min-Max Normalization
#Min-Max Normalization for Price

df['Price_MinMax']=(df['Price']-df['Price'].min())/(df['Price'].max()-df['Price'].min())
print("\nMin-Max Normalized price:")
print(df[['Product','Price','Price_MinMax']])

Min-Max Normalized price:
      Product  Price  Price_MinMax
0      Laptop  55000      0.675676
1      Mobile  30000      0.000000
2      Tablet  67000      1.000000
3  Headphones  30000      0.000000
4  Smartwatch  55600      0.691892
5      Camera  45000      0.405405

In [13]:
df['Discount_MinMax']=(df['Discount']-df['Discount'].min())/(df['Discount'].max()-df['Discount'].min())
print("\nMin-Max Normalized prDiscountce:")
print(df[['Product','Discount','Discount_MinMax']])

Min-Max Normalized prDiscountce:
      Product  Discount  Discount_MinMax
0      Laptop        10             0.25
1      Mobile        20             0.75
2      Tablet        15             0.50
3  Headphones        25             1.00
4  Smartwatch        10             0.25
5      Camera         5             0.00

In [21]:
#Normalized Multiple Columns
cols=['Price','Units_sold','Discount']
df_norm=(df[cols]-df[cols].min())/(df[cols].max()-df[cols].min())
print("\nMin-Max Normalized Data:")
df[cols] = df_norm
df_norm

Min-Max Normalized Data:

      Price  Units_sold  Discount
0  0.675676    0.000000      0.25
1  0.000000    0.312500      0.75
2  1.000000    0.656250      0.50
3  0.000000    1.000000      1.00
4  0.691892    0.625000      0.25
5  0.405405    0.140625      0.00

In [24]:
#2. Z-Score Normalization (Standardization)
df['Units_Zscore']=df['Units_sold']-df['Units_sold'].mean()/df['Units_sold'].std()
print("\nZ-Score Normalized Data:")
print(df[['Product','Units_sold','Units_Zscore']])

Z-Score Normalized Data:
      Product  Units_sold  Units_Zscore
0      Laptop    0.000000     -1.224489
1      Mobile    0.312500     -0.911989
2      Tablet    0.656250     -0.568239
3  Headphones    1.000000     -0.224489
4  Smartwatch    0.625000     -0.599489
5      Camera    0.140625     -1.083864

In [25]:
#3. Decimal Scaling
df['Price_Decimal']=df['Price']/100000
print("\nDecimal Scaled Data:")
print(df[['Product','Price','Price_Decimal']])

Decimal Scaled Data:
      Product     Price  Price_Decimal
0      Laptop  0.675676       0.000007
1      Mobile  0.000000       0.000000
2      Tablet  1.000000       0.000010
3  Headphones  0.000000       0.000000
4  Smartwatch  0.691892       0.000007
5      Camera  0.405405       0.000004

#**Part B: Turning Categorical Variables into Quantitative Variables in Python**

In [29]:
data={
    'Order_ID':[101,102,103,104,105,106],
    'Customer_Gender':['Male','Female','Male','Female','Male','Female'],
    'Payment_Mode':['Credit Card','COD','Debit Card','COD','Credit Card','COD'],
    'Product_Category':['Electronics','Clothing','Electronics','Clothing','Electronics','Clothing'],
    'City':['New York','Los Angeles','New York','Los Angeles','New York','Los Angeles'],
    'Oder_Value':['4500','2300','3200','5200','1800','4100']
}
df=pd.DataFrame(data)
df

,Order_ID,Customer_Gender,Payment_Mode,Product_Category,City,Oder_Value
0,101,Male,Credit Card,Electronics,New York,4500
1,102,Female,COD,Clothing,Los Angeles,2300
2,103,Male,Debit Card,Electronics,New York,3200
3,104,Female,COD,Clothing,Los Angeles,5200
4,105,Male,Credit Card,Electronics,New York,1800
5,106,Female,COD,Clothing,Los Angeles,4100

In [34]:
#Method 1: Label Encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder ()
df['Customer_Gender_Encoded']=le.fit_transform(df['Customer_Gender'])
print (df)

   Order_ID Customer_Gender Payment_Mode Product_Category         City  \
0       101            Male  Credit Card      Electronics     New York
1       102          Female          COD         Clothing  Los Angeles
2       103            Male   Debit Card      Electronics     New York
3       104          Female          COD         Clothing  Los Angeles
4       105            Male  Credit Card      Electronics     New York
5       106          Female          COD         Clothing  Los Angeles

  Oder_Value  Customer_Gender_Encoded  Gender_Label
0       4500                        1             1
1       2300                        0             0
2       3200                        1             1
3       5200                        0             0
4       1800                        1             1
5       4100                        0             0

In [35]:
#Method 2: One-Hot Encoding
df_encoded=pd.get_dummies(df,columns=['Payment_Mode'])
print(df_encoded)

   Order_ID Customer_Gender Product_Category         City Oder_Value  \
0       101            Male      Electronics     New York       4500
1       102          Female         Clothing  Los Angeles       2300
2       103            Male      Electronics     New York       3200
3       104          Female         Clothing  Los Angeles       5200
4       105            Male      Electronics     New York       1800
5       106          Female         Clothing  Los Angeles       4100

   Customer_Gender_Encoded  Gender_Label  Payment_Mode_COD  \
0                        1             1             False
1                        0             0              True
2                        1             1             False
3                        0             0              True
4                        1             1             False
5                        0             0              True

   Payment_Mode_Credit Card  Payment_Mode_Debit Card
0                      True                    False
1                     False                    False
2                     False                     True
3                     False                    False
4                      True                    False
5                     False                    False

In [36]:
#Method 3:Dummy Encoding (Drop First)
df_dummy=pd.get_dummies(df,columns=['Product_Category'],drop_first=True)
print(df_dummy)

   Order_ID Customer_Gender Payment_Mode         City Oder_Value  \
0       101            Male  Credit Card     New York       4500
1       102          Female          COD  Los Angeles       2300
2       103            Male   Debit Card     New York       3200
3       104          Female          COD  Los Angeles       5200
4       105            Male  Credit Card     New York       1800
5       106          Female          COD  Los Angeles       4100

   Customer_Gender_Encoded  Gender_Label  Product_Category_Electronics
0                        1             1                          True
1                        0             0                         False
2                        1             1                          True
3                        0             0                         False
4                        1             1                          True
5                        0             0                         False

#**New Dataset Operations**

In [37]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/amazon_products_dataset_Expt-14.csv")

In [39]:
#1. Min-Max Normalization
# FOR PRICE
df['Price_MinMax']=(df['Price']-df['Price'].min())/(df['Price'].max()-df['Price'].min())
print("\nMin-Max Normalized price:")
print(df[['Product_ID','Price','Price_MinMax']])

Min-Max Normalized price:
   Product_ID  Price  Price_MinMax
0        P101    799      0.020243
1        P102   1499      0.048583
2        P103    699      0.016194
3        P104   2499      0.089069
4        P105   3999      0.149798
5        P106   1199      0.036437
6        P107    899      0.024291
7        P108   1899      0.064777
8        P109   5499      0.210526
9        P110    999      0.028340
10       P111   7999      0.311741
11       P112   4599      0.174089
12       P113   1599      0.052632
13       P114    699      0.016194
14       P115    899      0.024291
15       P116   6499      0.251012
16       P117   1199      0.036437
17       P118   1999      0.068826
18       P119   2999      0.109312
19       P120   1299      0.040486
20       P121    499      0.008097
21       P122   2499      0.089069
22       P123   8999      0.352227
23       P124    799      0.020243
24       P125   3499      0.129555
25       P126   4599      0.174089
26       P127  12999      0.514170
27       P128   2199      0.076923
28       P129    699      0.016194
29       P130   1499      0.048583
30       P131   9999      0.392713
31       P132   5999      0.230769
32       P133   3499      0.129555
33       P134  11999      0.473684
34       P135  15999      0.635628
35       P136    599      0.012146
36       P137    799      0.020243
37       P138    299      0.000000
38       P139    999      0.028340
39       P140   1499      0.048583
40       P141   2999      0.109312
41       P142  10999      0.433198
42       P143   4999      0.190283
43       P144  24999      1.000000
44       P145   1999      0.068826
45       P146   7999      0.311741
46       P147  18999      0.757085
47       P148   2499      0.089069
48       P149   3499      0.129555
49       P150    999      0.028340

In [40]:
# FOR RATING
df['Rating_MinMax']=(df['Rating']-df['Rating'].min())/(df['Rating'].max()-df['Rating'].min())
print("\nMin-Max Normalized rating:")
print(df[['Product_ID','Rating','Rating_MinMax']])

Min-Max Normalized price:
   Product_ID  Rating  Rating_MinMax
0        P101     4.3       0.428571
1        P102     4.5       0.714286
2        P103     4.1       0.142857
3        P104     4.6       0.857143
4        P105     4.4       0.571429
5        P106     4.2       0.285714
6        P107     4.0       0.000000
7        P108     4.3       0.428571
8        P109     4.7       1.000000
9        P110     4.2       0.285714
10       P111     4.6       0.857143
11       P112     4.5       0.714286
12       P113     4.4       0.571429
13       P114     4.1       0.142857
14       P115     4.2       0.285714
15       P116     4.6       0.857143
16       P117     4.3       0.428571
17       P118     4.4       0.571429
18       P119     4.5       0.714286
19       P120     4.3       0.428571
20       P121     4.0       0.000000
21       P122     4.4       0.571429
22       P123     4.6       0.857143
23       P124     4.2       0.285714
24       P125     4.5       0.714286
25       P126     4.4       0.571429
26       P127     4.7       1.000000
27       P128     4.3       0.428571
28       P129     4.2       0.285714
29       P130     4.3       0.428571
30       P131     4.6       0.857143
31       P132     4.5       0.714286
32       P133     4.4       0.571429
33       P134     4.6       0.857143
34       P135     4.7       1.000000
35       P136     4.1       0.142857
36       P137     4.2       0.285714
37       P138     4.0       0.000000
38       P139     4.3       0.428571
39       P140     4.4       0.571429
40       P141     4.5       0.714286
41       P142     4.6       0.857143
42       P143     4.4       0.571429
43       P144     4.7       1.000000
44       P145     4.3       0.428571
45       P146     4.6       0.857143
46       P147     4.5       0.714286
47       P148     4.4       0.571429
48       P149     4.3       0.428571
49       P150     4.2       0.285714

In [41]:
# FOR REVIEWS
df['Reviews_MinMax']=(df['Reviews']-df['Reviews'].min())/(df['Reviews'].max()-df['Reviews'].min())
print("\nMin-Max Normalized review:")
print(df[['Product_ID','Reviews','Reviews_MinMax']])

Min-Max Normalized review:
   Product_ID  Reviews  Reviews_MinMax
0        P101     1520        0.291005
1        P102      980        0.148148
2        P103      870        0.119048
3        P104     2100        0.444444
4        P105     3050        0.695767
5        P106     1750        0.351852
6        P107      620        0.052910
7        P108     1120        0.185185
8        P109     1850        0.378307
9        P110      760        0.089947
10       P111     4200        1.000000
11       P112     2100        0.444444
12       P113     1300        0.232804
13       P114      540        0.031746
14       P115      870        0.119048
15       P116     2300        0.497354
16       P117      760        0.089947
17       P118     1600        0.312169
18       P119     3500        0.814815
19       P120      980        0.148148
20       P121      420        0.000000
21       P122     1450        0.272487
22       P123     1250        0.219577
23       P124      720        0.079365
24       P125     2100        0.444444
25       P126      980        0.148148
26       P127     3100        0.708995
27       P128     1300        0.232804
28       P129      880        0.121693
29       P130      990        0.150794
30       P131     2100        0.444444
31       P132     1750        0.351852
32       P133     2500        0.550265
33       P134     1450        0.272487
34       P135     2100        0.444444
35       P136      450        0.007937
36       P137      900        0.126984
37       P138      600        0.047619
38       P139      720        0.079365
39       P140      520        0.026455
40       P141      850        0.113757
41       P142     1200        0.206349
42       P143     2100        0.444444
43       P144     1800        0.365079
44       P145     1400        0.259259
45       P146     2200        0.470899
46       P147     1650        0.325397
47       P148      980        0.148148
48       P149      870        0.119048
49       P150      760        0.089947

In [45]:
#2. Z-Score Normalization
df['Price_Zscore']=df['Price']-df['Price'].mean()/df['Price'].std()
print("\nZ-Score Normalized Data:")
print(df[['Product_ID','Price','Price_Zscore']])

Z-Score Normalized Data:
   Product_ID  Price  Price_Zscore
0        P101    799     798.15422
1        P102   1499    1498.15422
2        P103    699     698.15422
3        P104   2499    2498.15422
4        P105   3999    3998.15422
5        P106   1199    1198.15422
6        P107    899     898.15422
7        P108   1899    1898.15422
8        P109   5499    5498.15422
9        P110    999     998.15422
10       P111   7999    7998.15422
11       P112   4599    4598.15422
12       P113   1599    1598.15422
13       P114    699     698.15422
14       P115    899     898.15422
15       P116   6499    6498.15422
16       P117   1199    1198.15422
17       P118   1999    1998.15422
18       P119   2999    2998.15422
19       P120   1299    1298.15422
20       P121    499     498.15422
21       P122   2499    2498.15422
22       P123   8999    8998.15422
23       P124    799     798.15422
24       P125   3499    3498.15422
25       P126   4599    4598.15422
26       P127  12999   12998.15422
27       P128   2199    2198.15422
28       P129    699     698.15422
29       P130   1499    1498.15422
30       P131   9999    9998.15422
31       P132   5999    5998.15422
32       P133   3499    3498.15422
33       P134  11999   11998.15422
34       P135  15999   15998.15422
35       P136    599     598.15422
36       P137    799     798.15422
37       P138    299     298.15422
38       P139    999     998.15422
39       P140   1499    1498.15422
40       P141   2999    2998.15422
41       P142  10999   10998.15422
42       P143   4999    4998.15422
43       P144  24999   24998.15422
44       P145   1999    1998.15422
45       P146   7999    7998.15422
46       P147  18999   18998.15422
47       P148   2499    2498.15422
48       P149   3499    3498.15422
49       P150    999     998.15422

In [49]:
df['Rating_Zscore']=df['Rating']-df['Rating'].mean()/df['Rating'].std()
print("\nZ-Score Normalized Data:")
print(df[['Product_ID','Rating','Rating_Zscore']])

Z-Score Normalized Data:
   Product_ID  Rating  Rating_Zscore
0        P101     4.3     -18.228847
1        P102     4.5     -18.028847
2        P103     4.1     -18.428847
3        P104     4.6     -17.928847
4        P105     4.4     -18.128847
5        P106     4.2     -18.328847
6        P107     4.0     -18.528847
7        P108     4.3     -18.228847
8        P109     4.7     -17.828847
9        P110     4.2     -18.328847
10       P111     4.6     -17.928847
11       P112     4.5     -18.028847
12       P113     4.4     -18.128847
13       P114     4.1     -18.428847
14       P115     4.2     -18.328847
15       P116     4.6     -17.928847
16       P117     4.3     -18.228847
17       P118     4.4     -18.128847
18       P119     4.5     -18.028847
19       P120     4.3     -18.228847
20       P121     4.0     -18.528847
21       P122     4.4     -18.128847
22       P123     4.6     -17.928847
23       P124     4.2     -18.328847
24       P125     4.5     -18.028847
25       P126     4.4     -18.128847
26       P127     4.7     -17.828847
27       P128     4.3     -18.228847
28       P129     4.2     -18.328847
29       P130     4.3     -18.228847
30       P131     4.6     -17.928847
31       P132     4.5     -18.028847
32       P133     4.4     -18.128847
33       P134     4.6     -17.928847
34       P135     4.7     -17.828847
35       P136     4.1     -18.428847
36       P137     4.2     -18.328847
37       P138     4.0     -18.528847
38       P139     4.3     -18.228847
39       P140     4.4     -18.128847
40       P141     4.5     -18.028847
41       P142     4.6     -17.928847
42       P143     4.4     -18.128847
43       P144     4.7     -17.828847
44       P145     4.3     -18.228847
45       P146     4.6     -17.928847
46       P147     4.5     -18.028847
47       P148     4.4     -18.128847
48       P149     4.3     -18.228847
49       P150     4.2     -18.328847

In [47]:
#3. Decimal Scaling- Review and Price
df['Price_Decimal']=df['Price']/100000
print("\nDecimal Scaled Data:")
print(df[['Product_ID','Price','Price_Decimal']])

Decimal Scaled Data:
   Product_ID  Price  Price_Decimal
0        P101    799        0.00799
1        P102   1499        0.01499
2        P103    699        0.00699
3        P104   2499        0.02499
4        P105   3999        0.03999
5        P106   1199        0.01199
6        P107    899        0.00899
7        P108   1899        0.01899
8        P109   5499        0.05499
9        P110    999        0.00999
10       P111   7999        0.07999
11       P112   4599        0.04599
12       P113   1599        0.01599
13       P114    699        0.00699
14       P115    899        0.00899
15       P116   6499        0.06499
16       P117   1199        0.01199
17       P118   1999        0.01999
18       P119   2999        0.02999
19       P120   1299        0.01299
20       P121    499        0.00499
21       P122   2499        0.02499
22       P123   8999        0.08999
23       P124    799        0.00799
24       P125   3499        0.03499
25       P126   4599        0.04599
26       P127  12999        0.12999
27       P128   2199        0.02199
28       P129    699        0.00699
29       P130   1499        0.01499
30       P131   9999        0.09999
31       P132   5999        0.05999
32       P133   3499        0.03499
33       P134  11999        0.11999
34       P135  15999        0.15999
35       P136    599        0.00599
36       P137    799        0.00799
37       P138    299        0.00299
38       P139    999        0.00999
39       P140   1499        0.01499
40       P141   2999        0.02999
41       P142  10999        0.10999
42       P143   4999        0.04999
43       P144  24999        0.24999
44       P145   1999        0.01999
45       P146   7999        0.07999
46       P147  18999        0.18999
47       P148   2499        0.02499
48       P149   3499        0.03499
49       P150    999        0.00999

In [48]:
df['Reviews_Decimal']=df['Reviews']/10000
print("\nDecimal Scaled Data:")
print(df[['Product_ID','Reviews','Reviews_Decimal']])

Decimal Scaled Data:
   Product_ID  Reviews  Reviews_Decimal
0        P101     1520            0.152
1        P102      980            0.098
2        P103      870            0.087
3        P104     2100            0.210
4        P105     3050            0.305
5        P106     1750            0.175
6        P107      620            0.062
7        P108     1120            0.112
8        P109     1850            0.185
9        P110      760            0.076
10       P111     4200            0.420
11       P112     2100            0.210
12       P113     1300            0.130
13       P114      540            0.054
14       P115      870            0.087
15       P116     2300            0.230
16       P117      760            0.076
17       P118     1600            0.160
18       P119     3500            0.350
19       P120      980            0.098
20       P121      420            0.042
21       P122     1450            0.145
22       P123     1250            0.125
23       P124      720            0.072
24       P125     2100            0.210
25       P126      980            0.098
26       P127     3100            0.310
27       P128     1300            0.130
28       P129      880            0.088
29       P130      990            0.099
30       P131     2100            0.210
31       P132     1750            0.175
32       P133     2500            0.250
33       P134     1450            0.145
34       P135     2100            0.210
35       P136      450            0.045
36       P137      900            0.090
37       P138      600            0.060
38       P139      720            0.072
39       P140      520            0.052
40       P141      850            0.085
41       P142     1200            0.120
42       P143     2100            0.210
43       P144     1800            0.180
44       P145     1400            0.140
45       P146     2200            0.220
46       P147     1650            0.165
47       P148      980            0.098
48       P149      870            0.087
49       P150      760            0.076

In [51]:
# Turning categorical variables into quantitative variables
df=pd.read_csv("/content/Student-Dataset.csv")

In [52]:
#Method 1: Label Encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder ()
df['Placement_Status_Encoded']=le.fit_transform(df['Placement_Status'])
print (df)

   Roll_No  Gender  Department  CGPA  Number_of_Backlogs  \
0      101  Female    Computer   8.2                   0
1      102    Male          IT   7.5                   1
2      103  Female        ENTC   9.1                   0
3      104    Male  Mechanical   6.8                   2
4      105  Female    Computer   8.7                   0
5      106    Male       Civil   7.2                   3
6      107  Female          IT   8.9                   0
7      108    Male    Computer   6.5                   1
8      109  Female        ENTC   7.8                   0
9      110    Male  Mechanical   7.0                   2

   Attendance_Percentage Placement_Status  Salary  Placement_Status_Encoded
0                     92           Placed  450000                         1
1                     85       Not Placed       0                         0
2                     96           Placed  550000                         1
3                     78       Not Placed       0                         0
4                     88           Placed  480000                         1
5                     72       Not Placed       0                         0
6                     91           Placed  500000                         1
7                     80       Not Placed       0                         0
8                     84           Placed  420000                         1
9                     76       Not Placed       0                         0

In [53]:
#Method 2: One-Hot Encoding
df_encoded=pd.get_dummies(df,columns=['Department'])
print(df_encoded)

   Roll_No  Gender  CGPA  Number_of_Backlogs  Attendance_Percentage  \
0      101  Female   8.2                   0                     92
1      102    Male   7.5                   1                     85
2      103  Female   9.1                   0                     96
3      104    Male   6.8                   2                     78
4      105  Female   8.7                   0                     88
5      106    Male   7.2                   3                     72
6      107  Female   8.9                   0                     91
7      108    Male   6.5                   1                     80
8      109  Female   7.8                   0                     84
9      110    Male   7.0                   2                     76

  Placement_Status  Salary  Placement_Status_Encoded  Department_Civil  \
0           Placed  450000                         1             False
1       Not Placed       0                         0             False
2           Placed  550000                         1             False
3       Not Placed       0                         0             False
4           Placed  480000                         1             False
5       Not Placed       0                         0              True
6           Placed  500000                         1             False
7       Not Placed       0                         0             False
8           Placed  420000                         1             False
9       Not Placed       0                         0             False

   Department_Computer  Department_ENTC  Department_IT  Department_Mechanical
0                 True            False          False                  False
1                False            False           True                  False
2                False             True          False                  False
3                False            False          False                   True
4                 True            False          False                  False
5                False            False          False                  False
6                False            False           True                  False
7                 True            False          False                  False
8                False             True          False                  False
9                False            False          False                   True

In [54]:
#Method 3:Dummy Encoding (Drop First)
df_dummy=pd.get_dummies(df,columns=['Department'],drop_first=True)
print(df_dummy)

   Roll_No  Gender  CGPA  Number_of_Backlogs  Attendance_Percentage  \
0      101  Female   8.2                   0                     92
1      102    Male   7.5                   1                     85
2      103  Female   9.1                   0                     96
3      104    Male   6.8                   2                     78
4      105  Female   8.7                   0                     88
5      106    Male   7.2                   3                     72
6      107  Female   8.9                   0                     91
7      108    Male   6.5                   1                     80
8      109  Female   7.8                   0                     84
9      110    Male   7.0                   2                     76

  Placement_Status  Salary  Placement_Status_Encoded  Department_Computer  \
0           Placed  450000                         1                 True
1       Not Placed       0                         0                False
2           Placed  550000                         1                False
3       Not Placed       0                         0                False
4           Placed  480000                         1                 True
5       Not Placed       0                         0                False
6           Placed  500000                         1                False
7       Not Placed       0                         0                 True
8           Placed  420000                         1                False
9       Not Placed       0                         0                False

   Department_ENTC  Department_IT  Department_Mechanical
0            False          False                  False
1            False           True                  False
2             True          False                  False
3            False          False                   True
4            False          False                  False
5            False          False                  False
6            False           True                  False
7            False          False                  False
8             True          False                  False
9            False          False                   True